### ISSUE TITLE
Should we include 'BusinessType' as categorical column or a text column(using CountVectorizer)?

### ISSUE THREAD

**Issue by Prabh95** [UBC-MDS/New_Businesses_Survival_Prediction#12]
We have a column in our combined dataset as 'BusinessType'. I was wondering what would be the right way to encode it.

**Comment by beth-ouyang** [comment]
@Prabh95, I tried to include `BusinessType` as categorical column at first. However, I've noticed that there were over 100 types, and some of them were related to each others by sharing some common words, such as 'Manufacturer' and 'Manufacturer - Food'. In this case, I choosed to transformed this column by `CountVectorizer`, in order to obtain the common words.

**Comment by Prabh95** [comment]
Okay, this makes sense. Thanks Beth.

**Comment by Prabh95** [comment]
Okay, this makes sense. Thanks Beth.
